### ISSUE TITLE
Dynamically populate multiple targets from a variable

### ISSUE THREAD

**Issue by obitech** [cloudalchemy/ansible-node-exporter#131]
Hey, sorry if this is more of an Ansible / Jinja related question but I've been struggling for a while with this. Please let me know if this is not the right place to ask this.

I want to set multiple targets from a variable that is in form of a list (my inventory, essentially):

```json
"groups": {
    "all": [
        "10.0.0.1", 
        "10.0.0.2", 
        "10.0.0.3"
    ], 
    "db": [
        "10.0.0.2", 
        "10.0.0.3"
    ], 
    "grafana": [
        "10.0.0.1"
    ], 
    "prometheus": [
        "10.0.0.1"
    ],
}
```

I tried:

```yaml
prometheus_targets:
  databases:
    - targets: "{{ groups['db'] | to_nice_yaml(indent=4) }}"

prometheus_scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "localhost:9090"
  - job_name: "databases"
    file_sd_configs:
      - files:
        - "{{ prometheus_config_dir }}/file_sd/databases.yml"
```

But this will get the indentation wrong:

```yaml
$ cat databases.yml
- targets: '- 10.36.22.133

    - 10.36.22.137

    '
```

Is there any way I can configure targets dynamically with this role?
