### ISSUE TITLE
node_exporter can not be updated when node_exporter_binary_local_dir is set

### ISSUE THREAD

**Issue by appliedprivacy** [cloudalchemy/ansible-node-exporter#160]
**What happened?**

After changing
```
node_exporter_binary_local_dir: node_exporter-1.0.0.linux-amd64
```
to
```
node_exporter_binary_local_dir: node_exporter-1.0.1.linux-amd64
```

I somewhat expected the role to copy the new version to the servers,
but install.yml is [ignored](https://github.com/cloudalchemy/ansible-node-exporter/blob/7f520dc64ba6137bab1f2c8c28a08addcf3e24ab/tasks/main.yml#L10) after the first playbook run and the version on the servers is not updated.

Moving the task "propagate locally distributed node_exporter binary" from install.yml to main.yml right after the install.yml import would solve this.

**How to reproduce it (as minimally and precisely as possible)**:
run this playbook:
```
- hosts: server
  roles:
    - ansible-node-exporter
  vars:
    node_exporter_binary_local_dir: /home/user/prometheus_bin/node_exporter-1.0.0.linux-amd64
```
then run this playbook:
```
- hosts: server
  roles:
    - ansible-node-exporter
  vars:
    node_exporter_binary_local_dir: /home/user/prometheus_bin/node_exporter-1.0.1.linux-amd64
```

**Environment**

* Role version:

0.21.0

* Ansible playbook execution Logs:

Task is skipped on second run since the node_exporter file exists on the server already:
```
TASK [ansible-node-exporter : Propagate node_exporter binaries] ********************************************************************************************
skipping: [server]
```
