### ISSUE TITLE
FreeBSD support 

### ISSUE THREAD

**Issue by appliedprivacy** [cloudalchemy/ansible-node-exporter#161]
Hi,
would you accept PRs to add FreeBSD support to your role?
thanks!

**Comment by paulfantom** [comment]
If it has systemd as an init it can be added.

**Comment by appliedprivacy** [comment]
Would you mind elaborating on why you feel that to be a requirement? 
compared to using the provided 1.0.1 package 
```
package:
  name: node_exporter
  state: enabled

service:
  name: node_exporter
  state: enabled
```
