### ISSUE TITLE
Unable to use role on MacOS - Python quit unexpectedly

### ISSUE THREAD

**Issue by waza-ari** [cloudalchemy/ansible-node-exporter#168]
**What happened?**

I'm trying to use the role to install node-exporter on a CentOS host from my MacOS machine. All other tasks from the playbook, involving various other roles such as docker work fine. The task "Get Checksum" fails with a strange error, see below. In parallel, a system dialogue shows up mentioning that Python quit unexpectedly.

**Did you expect to see some different?**

I'd expect the role to work :)

**How to reproduce it (as minimally and precisely as possible)**:

I'm just using the following code snipped in my playbook:

```
- hosts: prometheus_monitoring
  remote_user: ansible
  become: yes
  roles:
    - role: cloudalchemy.node-exporter
  vars:
    node_exporter_basic_auth_users:
      my_username: "{{ node_exporter_basic_auth_password }}"
```

**Environment**

```
ansible-playbook --version
WARNING: Executing a script that is loading libcrypto in an unsafe way. This will fail in a future version of macOS. Set the LIBRESSL_REDIRECT_STUB_ABORT=1 in the environment to force this into an error.
ansible-playbook 2.9.7
  config file = /Users/dherrman/AnsibleProjects/makerspace-ansible/ansible.cfg
  configured module search path = [u'/Users/dherrman/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.16 (default, Feb 29 2020, 01:55:37) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
```

* Role version:

    `0.21.0`

* Ansible version information:

    See environment
* Variables:

None relevant to the issue I believe

* Ansible playbook execution Logs:

```
TASK [cloudalchemy.node-exporter : Get checksum list from github] **************
task path: /Users/<username>/AnsibleProjects/<project>-ansible/roles/cloudalchemy.node-exporter/tasks/preflight.yml:99
ERROR! A worker was found in a dead state
```

**Anything else we need to know?**:
