### ISSUE TITLE
Adding option to configure collectors

### ISSUE THREAD

**Issue by paulfantom** [cloudalchemy/ansible-node-exporter#18]
It would be nice to have an option to configure collectors.

My proposal is to depend on collectors enabled by default in node_exporter and change var `node_exporter_enabled_collectors` into `node_exporter_enabled_collectors` which would have values like:
```
node_exporter_enabled_collectors:
- timex
- filesystem:
    option_a: value
    option_b: val
```
