### ISSUE TITLE
Textfile directory option missing from service unit file when set to default

### ISSUE THREAD

**Issue by parmsib** [cloudalchemy/ansible-node-exporter#181]
**What happened?**
As per this part of the README 
![image](https://user-images.githubusercontent.com/3922981/95576642-14964600-0a31-11eb-9e4a-552cdc5bec50.png)
the textfile directory should default to `/var/lib/node_exporter`.
However, when running the following playbook:
```
 - hosts: ubuntu                                                                                                                       
   vars:                                                                                                                               
     node_exporter_port: 9100                                                                                                          
     node_exporter_web_listen_address: "0.0.0.0:{{ node_exporter_port }}"                                                              
     node_exporter_enabled_collectors: [textfile]                                                                                      
   tasks:                                                                                                                              
     - name: Set up node exporter                                                                                                      
       import_role:                                                                                                                    
         name: cloudalchemy.node-exporter                                                                                              
       tags: node_exporter                                                                                                             
```
the systemd unit file ends up looking like this:

```
#
# Ansible managed
#

[Unit]
Description=Prometheus Node Exporter
After=network-online.target

[Service]
Type=simple
User=node-exp
Group=node-exp
ExecStart=/usr/local/bin/node_exporter \
    --collector.textfile \
    --web.listen-address=0.0.0.0:9100

SyslogIdentifier=node_exporter
Restart=always

PrivateTmp=yes
ProtectHome=yes
NoNewPrivileges=yes

ProtectSystem=strict
ProtectControlGroups=true
ProtectKernelModules=true
ProtectKernelTunables=yes

[Install]
WantedBy=multi-user.target
```
which is missing the `--collector.textfile.directory` option, making Node Exporter default to `""`, which
is not what the README of this role specifies.

**Did you expect to see some different?**
Yes. I expected the Node Exporter to be set up to have textfile look in `/var/lib/node_exporter`.
**How to reproduce it (as minimally and precisely as possible)**:
See above.
**Environment**

* Role version:
```
- src: cloudalchemy.node-exporter
  version: 0.14.0
```
* Ansible version information:

    `ansible --version`
```
ansible 2.9.13
...
  python version = 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) [GCC 7.3.0]
```

* Variables:

See above
