### ISSUE TITLE
Equal sign "=" not working with systemd

### ISSUE THREAD

**Issue by Tuxem** [cloudalchemy/ansible-node-exporter#238]
Hi

If we use filesystem, equal sign needs to be removed (cf https://github.com/prometheus/node_exporter/issues/990)
Ref : https://github.com/cloudalchemy/ansible-node-exporter/blob/18ff8f8833b1e357ce91bee6832c3a3d16e709f2/templates/node_exporter.service.j2#L19

To test try the node_exporter on a server with nfs mount and disable nfs4 fs check :

```
node_exporter_enabled_collectors:
  - systemd
  - textfile:
      directory: "{{ node_exporter_textfile_dir }}"
  - filesystem:
      ignored-mount-points: "^/(sys|proc|dev)($|/)"
      ignored-fs-types: "^nfs4$"
```
