### ISSUE TITLE
node_exporter_textfile_dir doesn't enable corresponding collector

### ISSUE THREAD

**Issue by sfuerte** [cloudalchemy/ansible-node-exporter#241]
**What happened?**
Using the variable doesn't enable `textfile` collector in `systemd` service file.

**Did you expect to see some different?**
Using the subject variable should automatically enable `collector.textfile.directory` param

* Variables:

```
      ansible.builtin.include_role:
        name: cloudalchemy.node_exporter
      vars:
        node_exporter_version: "1.2.2"
        node_exporter_web_listen_address: "127.0.0.1:9100"
        node_exporter_enabled_collectors: []
        node_exporter_disabled_collectors:
          - "bonding"
          - "fibrechannel"
          - "infiniband"
          - "nfs"
          - "nfsd"
          - "pressure"
          - "rapl"
          - "thermal_zone"
          - "uname"
        node_exporter_textfile_dir: "/var/lib/prometheus"
```
