### ISSUE TITLE
Encryption not working for basic authentication

### ISSUE THREAD

**Issue by lcrawfo** [cloudalchemy/ansible-node-exporter#257]
**What happened?**
The node exporter config has the password as *0

**Did you expect to see some different?**
Password should be a proper hash

**How to reproduce it (as minimally and precisely as possible)**:
`
- name: "Install node exporter"
  hosts: all
  gather_facts: true
  tags:
    - node
  vars_files:
    - vars/node-exporter.yml

  tasks:
    - name: "Install bcrypt"
      pip:
        name:
          - bcrypt
        executable: pip3

    - name: "Install node exporter"
      include_role:
        name: cloudalchemy.node_exporter
`

**Environment**

Installing onto ubuntu machine

* Role version:

2.0.0

* Ansible version information:

ansible [core 2.11.2]
python version = 3.8.10
jinja version = 3.0.1

* Variables:

node-exporter.yml contains

`
node_exporter_basic_auth_users:
  username: password
`

* Ansible playbook execution Logs:

```
changed: [rfi-ai-dev-ws-ostack-test-01] => changed=true
  checksum: 81695d57d6b1575ba31829ff7f5e91e8bf548a43
  dest: /etc/node_exporter/config.yaml
  diff: []
  gid: 0
  group: root
  invocation:
    module_args:
      _original_basename: config.yaml.j2
      attributes: null
      backup: false
      checksum: 81695d57d6b1575ba31829ff7f5e91e8bf548a43
      content: null
      dest: /etc/node_exporter/config.yaml
      directory_mode: null
      follow: false
      force: true
      group: root
      local_follow: null
      mode: 420
      owner: root
      remote_src: null
      selevel: null
      serole: null
      setype: null
      seuser: null
      src: <location>/.ansible/tmp/ansible-tmp-1641306365.1400058-1503729-120309611669019/source
      unsafe_writes: false
      validate: null
  md5sum: 12f3679e43b06af2901539dd7ba38373
  mode: '0644'
  owner: root
  size: 63
  src: <location>/.ansible/tmp/ansible-tmp-1641306365.1400058-1503729-120309611669019/source
  state: file
  uid: 0
```

(location - section of file path redacted)

**Anything else we need to know?**:

There is no error visible when ran with -vvv, yet still doesn't work correctly
