### ISSUE TITLE
Issue running the Role

### ISSUE THREAD

**Issue by ppadial** [cloudalchemy/ansible-node-exporter#82]
When i tried to apply the role:

```yaml
# ------------------------------------------------------------------------------
# Node Exporter Service
# ------------------------------------------------------------------------------
- hosts:
    - node-exporters
  roles:
    - role: cloudalchemy.node-exporter
      node_exporter_version: 0.17.0
      node_exporter_enabled_collectors:
        - supervisord
        - systemd
        - tcpstat
        - textfile

# ------------------------------------------------------------------------------
# Firewall Rules
# ------------------------------------------------------------------------------
- hosts:
    - node-exporters
  tasks:
    - name: Open 9100/tcp port in the firewall
      firewalld:
        port: 9100/tcp
        permanent: yes
        immediate: yes
        state: enabled
      when: ansible_os_family == 'RedHat'
```

i got this error
```
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/ppadial/.ansible/tmp/ansible-tmp-1554487030.581331-239264549754786/ /Users/ppadial/.ansible/tmp/ansible-tmp-1554487030.581331-239264549754786/AnsiballZ_get_url.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=scrsjkfwaegntxilsjtpmzdkousxbdah] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS
 /usr/local/Cellar/ansible/2.7.9/libexec/bin/python3.7 /Users/ppadial/.ansible/tmp/ansible-tmp-1554487030.581331-239264549754786/AnsiballZ_get_url.py'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c 'echo ~ppadial && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/ppadial/.ansible/tmp/ansible-tmp-1554487028.519246-130314029194652/ > /dev/null 2>&1 && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/ppadial/.ansible/tmp/ansible-tmp-1554487032.687249-126806156839976 `" && echo ansible-tmp-1554487032.687249-126806156839976="` echo /Users/ppadial/.ansible/tmp/ansible-tmp-1554487032.687249-126806156839976 `" ) && sleep 0'
FAILED - RETRYING: Download node_exporter binary to local folder (3 retries left).Result was: {
    "attempts": 3,
    "changed": false,
    "module_stderr": "Sorry, try again.\n[sudo via ansible, key=akey] password: \nsudo: 1 incorrect password attempt\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "retries": 6
}
```

Any ideas?
